<?php

/**
 * @file
 * Allows users with valid permissions to tag profile fields created
 * from the profile module as required fields for a
 * users profile to be considered complete.
 */

/**
 * Implements hook_init().
 */
function pcp_init() {
  // needed to execute pcp_form_user_admin_settings_alter()
  include_once('pcp.admin.inc');
}

/**
 * Implements hook_theme().
 */
function pcp_theme($existing, $type, $theme, $path) {
  return array(
    'pcp_template' => array(
      'template' => 'pcp-template',
      'variables' => array('complete_data' => NULL),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function pcp_permission() {
  return array(
    'administer pcp' => array(
      'title' => t('Administer Profile Complete Percentages'),
      'description' => t('Allows a user to configure which fields to be considered complete.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function pcp_menu() {
  $items['admin/config/people/pcp'] = array(
    'title' => 'Profile Complete Percentages',
    'description' => 'Tag profile fields as required for percent complete handling.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pcp_admin_settings'),
    'access arguments' => array('administer pcp'),
    'file' => 'pcp.admin.inc',
    'weight' => 10,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function pcp_block_info() {

  // Create block for core user profiles.
  $blocks['pcp_profile_percent_complete'] = array(
    'info' => t('Profile Complete Percentage - Core Profile'),
  );

  // Create a block for each profile2 profile type.
  if ($profile2_entity = entity_get_info('profile2')) {
    foreach ($profile2_entity['bundles'] as $bundle => $values) {
      $blocks['pcp_profile2_' . $bundle] = array(
        'info' => t('Profile Complete Percentage - ' . $values['label']),
      );
    }
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pcp_block_view($delta = '') {
  global $user;

  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'pcp_profile_percent_complete':


      $out = pcp_get_complete_percentage_data('user', 'user', $user);
      $hide = variable_get('pcp_hide_block_on_complete', 0);

      if (($hide && ($out['incomplete'] == 0)) || empty($out)) {
        $subject = '';
        $content = '';
      }
      else {
        $subject = t('Profile Complete');
        $content = theme('pcp_template', $out);
      }

      $block['subject'] = $subject;
      $block['content'] = $content;

      break;

    // Generate content for each profile2 profile type's pcp block.
    default:

      if ($profile2_entity = entity_get_info('profile2')) {
        foreach ($profile2_entity['bundles'] as $bundle => $values) {
          if ($delta == 'pcp_profile2_' . $bundle) {

            $out = pcp_get_complete_percentage_data('profile2', $bundle, $user);
            $hide = variable_get('pcp_profile2_' . $bundle . '_hide_block_on_complete', 0);

            // If the block should be hidden, hide it.
            if (($hide && ($out['incomplete'] == 0)) || empty($out)) {
              $subject = '';
              $content = '';
            }
            else {
              $subject = t('Profile Complete');
              $content = theme('pcp_template', $out);
            }

            $block['subject'] = t('Profile Complete Percentage - ' . $values['label']);
            $block['content'] = $content;
          }
        }
      }
      break;
  }


  return $block;
}

/**
 * Get the profile complete percentage data for a given user.
 *
 * @param $user
 *   User object
 *
 * @return
 *   PCP data array.
 */
function pcp_get_complete_percentage_data($entity_type, $bundle, $user) {
  $entity_fields = field_info_instances($entity_type, $bundle);

  $profile_fields = pcp_get_tagged_profile_fields(NULL, $entity_type, $bundle);
  $additional_fields = pcp_get_additional_tagged_fields();
  $fields = $profile_fields + $additional_fields;

  // We need to define these values here in case $data is returned early.
  $data = array();
  $data['entity_type'] = $entity_type;
  $data['bundle'] = $bundle;

  // If no fields have been tagged, indicate that the profile is complete.
  if (!$fields) {
    $data['current_percent'] = 100;
    $data['incomplete'] = 0;
    return $data;
  }

  $user_profile_values = pcp_get_user_profile_values($user->uid, $entity_type, $bundle);

  $user_additional_values = pcp_get_user_additional_values($user->uid, $entity_type, $bundle);
  $user_values = $user_profile_values + $user_additional_values;

  // Enumerate empty fields
  $empty_fields = array();
  foreach ($fields as $key => $field) {
    if (empty($user_values[$key])) {
      $empty_fields[$key] = $field;
    }
  }

  // If there is one empty field or more
  if ($empty_fields) {
    $data['uid'] = $user->uid;

    // Pick up a random field, we won't use shuffle because it reindex the array
    // keys
    $fiid = array_rand($empty_fields);

    if (is_numeric($fiid)) {
      $field_title = $entity_fields[$fields[$fiid]]['label'];
      $field_name = $fields[$fiid];
    }
    elseif ($fiid == 'user_picture') {
      $field_title = $fields[$fiid]['title'];
      $field_name = $fields[$fiid]['name'];
    }

    $data['nextfield_id'] = $fiid;
    $data['nextfield_title'] = $field_title;
    $data['nextfield_name'] = $field_name;
  }

  $fields_count = count($fields);
  $empty_fields_count = count($empty_fields);

  $completed_fields = $fields_count - $empty_fields_count;
  $current_percent = number_format(($completed_fields / $fields_count), 2) * 100;
  $next_percent = number_format((($completed_fields + 1) / $fields_count), 2) * 100;

  $data['completed']  = $completed_fields;
  $data['incomplete'] = $empty_fields_count;
  $data['total'] = $fields_count;

  $data['current_percent'] = $current_percent;
  $data['next_percent'] = $next_percent;

  return $data;
}

/**
 * Get all the profile fields stored in the system, tagged or not tagged.
 */
function pcp_get_profile_fields($params) {

  $instances = field_read_instances($params);
  $fields = array();
  foreach ($instances as $instance) {
    $fields[$instance['id']] = $instance['field_name'];
  }
  return $fields;
}

/**
 * Get all the profile fields that have been tagged.
 * If an $fiid is passed in, only the data for that field will be returned.
 *
 * @param $fiid
 *   (optional) NULL The field instance id of the field data should be returned for. If null, all fields
 *   are returned.
 * @param $entity_type
 *   (optional) NULL The type of entity to return fields for.
 * @param $bundle
 *   (optional) NULL The bundle to return fields for.
 *
 * @return
 *   field instance ID(s) and name(s).
 */
function pcp_get_tagged_profile_fields($fiid = NULL, $entity_type = NULL, $bundle = NULL) {
  $query = db_select('field_config_instance', 'fci');
  $query->addField('fci', 'id', 'fiid');
  $query->addField('fci', 'field_name', 'field_name');
  $query->join('profile_pcp', 'pcp', 'pcp.fiid = fci.id');


  if (isset($entity_type)) {
    $query->condition('entity_type', $entity_type);
  }

  if (isset($bundle)) {
    $query->condition('bundle', $bundle);
  }

  if (isset($fiid)) {
    $query->condition('fiid', $fiid);
  }

  $result = $query->execute();

  $fields = array();
  foreach ($result as $row) {
    $fields[$row->fiid] = $row->field_name;
  }

  return $fields;
}

/**
 * Get all other fields stored in the system that where not created by
 * the profile module. This allows additional PCP
 * support for other drupal features.
 */
function pcp_get_additional_fields() {
  $fields = array();

  // Enable user picture support.
  $fields['user_picture'] = array(
    'title' => 'User Picture',
    'name' => 'picture_upload',
  );

  return $fields;
}

/**
 * Get all additional tagged fields that where not created
 * using the profile module. This allows additional PCP
 * support for other drupal features.
 */
function pcp_get_additional_tagged_fields() {
  $fields = array();

  // Enable user picture support.
  if (variable_get('pcp_enable_user_picture', 0)) {
    $fields['user_picture'] = array(
      'fiid' => 'user_picture',
      'title' => 'User Picture',
      'name' => 'picture_upload',
    );
  }

  return $fields;
}

/**
 * Return a users profile field values that have been saved
 * for a given user.
 *
 * @param int $uid
 *   The uid of the user we are returning data for.
 * @param $entity_type
 *   The type of entity to return fields for.
 * @param $bundle
 *   (optional) NULL The bundle to return fields for
 *
 * @return assoc array of all profile fields for the user.
 */
function pcp_get_user_profile_values($uid, $entity_type, $bundle = NULL) {
  $fields = field_info_instances($entity_type, $bundle);
  $user = user_load($uid);
  $user_fields = array();

  // Grab profile values from core profile fields.
  if ($entity_type == 'user') {
    foreach ($fields as $field) {
      $fiid = $field['id'];
      $user_fields[$fiid] = $user->$field['field_name'];
    }
  }

  // If user has profile2 profile, grab values from it.
  elseif ($entity_type == 'profile2' && $profile = profile2_load_by_user($user, $bundle)) {
    foreach ($fields as $field_name => $field_values) {
      if ($field = $profile->$field_name) {
        $fiid = $field_values['id'];
        $user_fields[$fiid] = $field['und'][0];
      }
    }
  }

  // Note, entity type user will return empty fields, whereas entity type profile2 will
  // only return non-empty fields.

  return $user_fields;
}

/**
 * Return a users additional field values that have been saved
 * for a given user.
 *
 * @param int $uid
 *   The uid of the user we are returning data for.
 * @param $entity_type
 *   The type of entity to return fields for.
 * @param $bundle
 *   (optional) NULL The bundle to return fields for
 *
 * @return assoc array of all profile fields for the user.
 */
function pcp_get_user_additional_values($uid, $entity_type, $bundle = NULL) {
  $values = array();
  if ($uid && $entity_type == 'user') {
    $account = user_load($uid);
    $values['user_picture'] = $account->picture;
  }
  return $values;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * We need an extra submit handler to delete the PCP field settings when a field is deleted
 */
function pcp_form_field_ui_field_delete_form_alter(&$form, &$form_state) {
  if ($form['entity_type'] == 'profile2') {
    $form['#submit'] = array_merge(array('pcp_delete_field_requireness'), $form['#submit']);
  }
}

/**
 * Called when a user deletes a profile field
 * We then need to delete the pcp value too
 */
function pcp_delete_field_requireness($form, &$form_state) {
  $instance = field_info_instance($form_state['values']['entity_type'], $form_state['values']['field_name'], $form_state['values']['bundle']);
  $query = db_delete('profile_pcp')
    ->condition('fiid', $instance['id'])
    ->execute();
}

/**
 * Process variables for pcp-template.tpl.php.
 *
 * @see pcp-template.tpl.php
 */
function template_preprocess_pcp_template(&$variables) {
  if (isset($variables['nextfield_name'])) {
    $field = field_info_instance($variables['entity_type'], $variables['nextfield_name'], $variables['bundle']);
    // Generate URL to edit next field for core user profile.
    if ($variables['entity_type'] == 'user') {
      $input_name = 'edit-' . str_replace('_', '-', $variables['nextfield_name']);
      $user_edit_path = 'user/' . $variables['uid'] . '/edit';
      $variables['next_path'] = url($user_edit_path, array('absolute' => TRUE, 'fragment' => $input_name));
    }

    // Generate URL to edit next field for profile2 profile.
    elseif ($variables['entity_type'] == 'profile2') {
      $bundle = $variables['bundle'];
      $input_name = 'edit-profile-' . str_replace('_', '-', $bundle) . '-' . str_replace('_', '-', $variables['nextfield_name']);
      $profile_edit_path = 'profile-' . $bundle . '/' . $variables['uid'] . '/edit';
      $variables['next_path'] = url($profile_edit_path, array('absolute' => TRUE, 'fragment' => $input_name));
    }
  }
}